### ISSUE TITLE
[DISCUSSION] Some config values should be optional

### ISSUE THREAD

**Issue by bbalet** [derricksmith/phpsaml#4]
I was able to use the plugin with the latest stable version of GLPI (it looks OK with v4 RC4, but I'd need to do more tests) and Google as an Identity Provider. Here are some feedback:

 - Some IdP doesn't support logout scenario (it is the case of Google SAML), in this case I think you should delegate the logout to GLPI (it would simply clear the session) if the logout URL is empty.
 - You should make optional the SP's key and certificate fields. Because many IdP doesn't require a signed response (although it is a good practice). In your future doc ;) you might suggest this page from OneLogin that helps to generate a valid x509 certificate and key: https://www.samltool.com/self_signed_certs.php

**Comment by derricksmith** [comment]
I made the Idp cert, key and slo fields optional but experienced some issues with the empty slo field.   It appears that logout.php redirects back to index.php where I'm hooking the authentication process.  This kicks off another SSO request to the Idp and since it never received a logout request it responds successfully.  The end result is that the user is redirected back to GLPI and logged in.

**Comment by derricksmith** [comment]
The latest update addresses the SLO issue.  Let me know if this resolves for you.

**Comment by bbalet** [comment]
I have tested it and it works perfectly.

Just for your information, [Auth0](https://auth0.com/) offers a free account for testing with something else than Microsoft AD.
